# Generated by Django 3.2.7 on 2022-08-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-id',), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-id',), 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-id',), 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
