# Generated by Django 3.2.7 on 2022-08-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ('-id',), 'verbose_name': 'Carga', 'verbose_name_plural': 'Cargas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('-id',), 'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-id',), 'verbose_name': 'Transferencia', 'verbose_name_plural': 'Transferencias'},
        ),
    ]
